## Environment Identifier
This model will be trained on google maps images of overview images of various ecosystems and use supervised categorical machine learning to identify various types of terestrial ecosystems:
#### forest
#### desert
#### grassland
#### tundra
I am not sure if I want to add urban to the list of ecosystems

### Import all the stuff for models

In [1]:
import os                                
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # silence all the tensorflow warnings
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

### import images from the directories

In [2]:
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing import image_dataset_from_directory

import matplotlib.pyplot as plt
base_dir = "./ecosystems/"
forest_dir = os.path.join(base_dir, 'forest/')
grassland_dir = os.path.join(base_dir, 'grassland/')
tundra_dir = os.path.join(base_dir, 'tundra/')
desert_dir = os.path.join(base_dir, 'desert/')

### train on just forest and desert, use k-means clustering.
I am getting impatiant, I just want to see if it can even get forest vs. desert with about 500 pics of each

In [3]:
dataset = image_dataset_from_directory(base_dir, labels='inferred',image_size = (250,250),batch_size=64)
iterator = iter(dataset)
batch_size = 64
num_batches = 22
x_train = []
y_train = []


Found 1408 files belonging to 2 classes.


In [63]:
print(type(dataset))
print(len(dataset))

<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>
137


In [351]:
from tensorflow.keras import layers
from tensorflow.keras.losses import binary_crossentropy
model = keras.models.Sequential()
model.add(layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(250, 250, 3)))
model.add(layers.MaxPooling2D(pool_size=(2,2)))

model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')

In [352]:
iterator = iter(dataset)
batch_size = 64
num_epochs = 2
num_batches_per_epoch = int(1408/64)
for epoch in range(num_epochs):
    print(f"---------------- on epoch number: {epoch+1}")
    iterator = iter(dataset)
    for batch in range(num_batches_per_epoch):
        print(f'batch #{batch}')
        x_batch, y_batch = next(iterator)
        model.fit(x_batch, y_batch)

---------------- on epoch number: 1
batch #0
1/1 [==============================] - 1s 727ms/step - loss: 33.6281
batch #1
1/1 [==============================] - 0s 346ms/step - loss: 13257.2773
batch #2
1/1 [==============================] - 0s 355ms/step - loss: 14664.1055
batch #3
1/1 [==============================] - 0s 351ms/step - loss: 5788.6445
batch #4
1/1 [==============================] - 0s 341ms/step - loss: 1279.0181
batch #5
1/1 [==============================] - 0s 347ms/step - loss: 3991.9275
batch #6
1/1 [==============================] - 0s 340ms/step - loss: 669.8765
batch #7
1/1 [==============================] - 0s 335ms/step - loss: 1597.7090
batch #8
1/1 [==============================] - 0s 336ms/step - loss: 1240.9758
batch #9
1/1 [==============================] - 0s 333ms/step - loss: 420.0269
batch #10
1/1 [==============================] - 0s 338ms/step - loss: 0.0000e+00
batch #11
1/1 [==============================] - 0s 336ms/step - loss: 273.0587
batc

1/1 [==============================] - 0s 345ms/step - loss: 0.0000e+00
batch #63
1/1 [==============================] - 0s 342ms/step - loss: 0.0000e+00
batch #64
1/1 [==============================] - 0s 344ms/step - loss: 0.0000e+00
batch #65
1/1 [==============================] - 0s 341ms/step - loss: 20.5622
batch #66
1/1 [==============================] - 0s 345ms/step - loss: 332.9701
batch #67
1/1 [==============================] - 0s 345ms/step - loss: 0.0000e+00
batch #68
1/1 [==============================] - 0s 340ms/step - loss: 533.0807
batch #69
1/1 [==============================] - 0s 339ms/step - loss: 240.9626
batch #70
1/1 [==============================] - 0s 343ms/step - loss: 0.0000e+00
batch #71
1/1 [==============================] - 0s 340ms/step - loss: 610.2748
batch #72
1/1 [==============================] - 0s 343ms/step - loss: 0.0000e+00
batch #73
1/1 [==============================] - 0s 341ms/step - loss: 0.0000e+00
batch #74
1/1 [======================

In [353]:
test_dir = './test'
test_images= image_dataset_from_directory(test_dir, labels='inferred',image_size = (250,250),batch_size=7)

Found 7 files belonging to 2 classes.


In [354]:
(test_data,test_labels) = next(iter(test_images))
pred = model.predict(test_data)
print(pred)
print(test_labels)
print(len(test_data))
print(len(test_data[7][0][0]))


1/1 [==============================] - 0s 55ms/step
[[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]]
tf.Tensor([0 1 1 0 1 1 0], shape=(7,), dtype=int32)
7


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:CPU:0}} slice index 7 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

## Question:  Why are all the predictions perfect even though I put a desert picture in the forest directory?

In [356]:
path = './test/'
images = tf.keras.utils.image_dataset_from_directory(path,image_size=(250,250))
(imgs,labels) = next(iter(images))
preds = model.predict(imgs)
print(preds)
print(labels)

Found 7 files belonging to 2 classes.
1/1 [==============================] - 0s 57ms/step
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]]
tf.Tensor([1 0 1 1 1 0 0], shape=(7,), dtype=int32)


In [359]:
import numpy as np
import matplotlib.pyplot as plt
file_path = "./test/forest/forest1.png"

#path = './test/'
image = tf.io.read_file(file_path)
image = tf.image.decode_jpeg(image, channels=3)
image = tf.image.resize(image, [250, 250])
#plt.imshow(image)
#plt.show()
print(len(image))
print(len(image[0]))
print(len(image[0][0]))

#images = tf.constant(image,shape=(None,image.ndim),dtype='float32')

pred = model.predict(np.array([image]))
print(pred)


250
250
3
1/1 [==============================] - 0s 41ms/step
[[1.]]
